init:
  - git config --global core.autocrlf true
platform: x64
environment:
  nodejs_version: "8"
cache:
  - node_modules
  - '%USERPROFILE%\.gitbook'
install:

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

  # Install InnoSetup
  - choco install -y InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

  # Build the things
  - yarn

  # Edit the package.json if this isn't an official release
  - IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (node .\scripts\dev-version.js)

  # Define the travis tag as "latest-dev" if its not already defined
  - IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (SET APPVEYOR_REPO_TAG_NAME=latest-dev)

  # Nice dev helpers to verify our env
  - scripts\appveyor-env.bat

  # Sanity checks
  - node --version
  - yarn --version
  - node bin\lando.js version
  # Iscc has no version option and returns exit code 1 by default
  # This can never fail but at least we can check the output to verify
  - iscc | echo

  # Run tests
  - yarn test

  # Make sure we can build the docs
  - yarn docs

build_script:

  # Build dev releases
  - yarn pkg:full
  - mkdir release
  - copy "dist\lando.exe" "release\lando-%APPVEYOR_REPO_TAG_NAME%.exe"

artifacts:
  - path: release\*.exe
    name: release

after_build:
  - ps: Get-ChildItem .\release\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName weezer }
deploy:
  - provider: GitHub
    description: v$(LANDO_VERSION)
    artifact: weezer
    draft: false
    auth_token:
      secure: 59olpXsQzG1FN5/M/VZJeMNdlwSoFn4L/Lefk/t3T4j39VF7y4paGsDG6CRuwZGD
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: S3
    access_key_id:
      secure: hheF7PGTvLnmq4LzzxZv6/TyzBmPHkhxOVuQFzXZrFQ=
    secret_access_key:
      secure: n2Wto8btzQ6w029bsvN5POyXfbKs5sL5G83AUjaDvmOkqsoxIL8ijh+md+CkY4BS
    bucket: installer.kalabox.io
    region: us-west-2
    set_public: true
    artifact: weezer
    on:
      branch: master
