product: lando
channel: stable
domain: lndo.site
mode: cli

dockerSupportedVersions:
  compose:
    min: "1.23.0"
    max: "1.26.2"
    link:
      linux: https://docs.docker.com/compose/install/#install-compose-on-linux-systems
  desktop:
    min: "2.1.0.0"
    max: "2.3.0.4"
    link:
      darwin: https://docs.docker.com/docker-for-mac/release-notes/
      win32: https://docs.docker.com/docker-for-windows/release-notes/
  engine:
    min: "18.09.3"
    max: "19.04.0"
    link:
      linux: https://docs.docker.com/engine/install/

landoFile: .lando.yml
stats:
  - report: true
    url: https://metrics.lando.dev
