product: lando
channel: stable
domain: lndo.site
mode: cli

dockerSupportedVersions:
  compose:
    min: "1.23.0"
    max: "1.29.0"
    link:
      linux: https://docs.docker.com/compose/install/#install-compose-on-linux-systems
  desktop:
    min: "2.1.0.0"
    max: "3.3.99"
    link:
      darwin: https://docs.docker.com/docker-for-mac/release-notes/
      win32: https://docs.docker.com/docker-for-windows/release-notes/
  engine:
    min: "18.09.3"
    max: "20.10.99"
    link:
      linux: https://docs.docker.com/engine/install/

landoFile: .lando.yml

# Overrides
stats:
  - report: false
    url: https://metrics.lando.dev
