http://devwithlando.io/:
  type: redirect
  to: http://{default}/
http://docs.devwithlando.io/:
  type: redirect
  to: http://docs.{default}/
http://lndo.io/:
  type: redirect
  to: http://{default}/
http://docs.lndo.io/:
  type: redirect
  to: http://docs.{default}/
http://{default}/:
  type: upstream
  upstream: site:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
http://docs.{default}/:
  type: upstream
  upstream: docs:http
  cache:
    headers: ['Accept', 'Accept-Language', 'Origin']
    default_ttl: 2600
    enabled: true
  ssi:
    enabled: false
